version: '3'
services:
  front:
    build: ./front
    volumes: 
      - ./front:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn install && yarn build && yarn start"
  front-build:
    build: ./nginx
    volumes:
      - ./front/build:/usr/share/nginx/html
    ports:
      - "3001:80"
    depends_on: 
      - front
  back:
    build: ./back
    volumes:
      - ./back:/app
    ports:
      - "4000:4000"
    command: rails s -p 4000 -b '0.0.0.0'
    depends_on: 
      - db
  db:
    build: ./postgres
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: chat_like_app
      POSTGRES_USER: sawai
      POSTGRES_PASSWORD: sawai
      POSTGRES_ROOT_PASSWORD: sawai
  socket:
    build: ./socket
    volumes:
      - ./socket:/app
    ports:
      - "8000:8000"
    command: sh -c "yarn install && node ./socket_server.js"
volumes:
  db_data: {}
