version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # - run:
      #     name: Build Docker Image
      #     command: docker-compose build
      - run:
          name: Up Docker Image
          command: |
                docker-compose -f up 
      # - run:
      #     name: Run tests
      #     command:
      - run:
          name: docker-compose -f down 
          command: |
                docker-compose -f down 
      # herokuに乗っける
      # - run:
      #     name: deploy on heroku
      #     command: |
