version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Up Docker Image
          command: docker-compose up -d
      # - run:
      #     name: コンテナに入ってみる
      #     command: docker exec -it project_front_1 sh
      # - run:
      #     name: Run tests
      #     command:
      - run:
          name: docker-compose down 
          command: |
                docker-compose down 
      # herokuに乗っける
      # - run:
      #     name: deploy on heroku
      #     command: |
