version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: docker-compose -f up -d
          command: |
                docker-compose -f up -d
      # - run:
      #     name: Run tests
      #     command:
      - run:
          name: docker-compose -f down -d
          command: |
                docker-compose -f down -d
      # herokuに乗っける
      # - run:
      #     name: deploy on heroku
      #     command: |
