development:
  secret_key_base: sawai

test:
  secret_key_base: sawai

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_storage_access_key_id: <%= ENV["ACCESS_KEY"] %>
  google_storage_secret_access_key: <%= ENV["SECRET_KEY"] %>